version: '3.8'

services:
  # Production-like build (serves static files)
  fahrschule-app:
    build: .
    ports:
      - "8906:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Development with hot reload
  fahrschule-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8907:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev
    restart: unless-stopped
